/**
 * Image utility functions for jersey image handling
 * Storage-first approach - Use pre-generated variants from Supabase Storage
 * Variants are generated by the generate-image-variants Edge Function during upload
 */

/**
 * Get Supabase URL from environment
 */
function getSupabaseUrl(): string {
	const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
	if (!url) {
		throw new Error('NEXT_PUBLIC_SUPABASE_URL not set');
	}
	return url;
}

/**
 * Get variant storage path from original storage path
 * Example: "jersey-id/1234567890-abc123.jpg" -> "jersey-id/1234567890-abc123-vision.jpg"
 *
 * This constructs the expected path for pre-generated variants in Supabase Storage.
 * Variants are generated by the `generate-image-variants` Edge Function during upload.
 */
export function getVariantStoragePath(
	originalPath: string,
	variant: 'vision' | 'gallery' | 'card'
): string {
	if (!originalPath) return originalPath;

	// Extract base name without extension
	const pathParts = originalPath.split('/');
	const fileName = pathParts[pathParts.length - 1];
	const baseName = fileName.replace(/\.[^.]+$/, ''); // Remove extension
	const jerseyId = pathParts[0]; // First part is jersey_id

	// Determine extension and suffix based on variant
	// These must match the Edge Function's naming convention
	const variantConfig = {
		vision: { suffix: '-vision', ext: '.jpg' },    // For AI Vision processing (max 2000x2000, JPEG Q80)
		gallery: { suffix: '-gallery', ext: '.webp' }, // For detail view (1200w, WebP Q70)
		card: { suffix: '-card', ext: '.webp' },       // For thumbnails (480w, WebP Q65)
	}[variant];

	const variantFileName = `${baseName}${variantConfig.suffix}${variantConfig.ext}`;
	return `${jerseyId}/${variantFileName}`;
}

/**
 * Build Supabase Storage public URL from storage path
 * @param storagePath - Storage path (e.g., "jersey-id/filename.jpg" or "jersey-id/filename-gallery.webp")
 * @param bucket - Storage bucket name (default: 'jersey_images')
 * @returns Full public URL to the file in Storage
 */
export function buildStorageUrl(
	storagePath: string,
	bucket: string = 'jersey_images'
): string {
	if (!storagePath) return '';

	const supabaseUrl = getSupabaseUrl();
	// Supabase public URL format: {supabaseUrl}/storage/v1/object/public/{bucket}/{path}
	return `${supabaseUrl}/storage/v1/object/public/${bucket}/${storagePath}`;
}

/**
 * Get variant public URL from original storage path
 * Constructs Supabase Storage public URL for the variant
 *
 * @param originalStoragePath - Storage path of the original image
 * @param variant - Variant type to retrieve
 * @returns Public Storage URL for the variant
 */
export function getVariantUrl(
	originalStoragePath: string,
	variant: 'vision' | 'gallery' | 'card'
): string {
	if (!originalStoragePath) return '';

	const variantPath = getVariantStoragePath(originalStoragePath, variant);
	return buildStorageUrl(variantPath);
}

/**
 * Derive WebP URL from original image URL
 * Replaces file extension with .webp
 * @deprecated Use getVariantUrl with 'gallery' or 'card' instead
 */
export function getWebPUrl(originalUrl: string): string {
	if (!originalUrl) return originalUrl;
	
	// If already webp, return as-is
	if (originalUrl.toLowerCase().endsWith('.webp')) {
		return originalUrl;
	}
	
	// Replace extension with .webp
	return originalUrl.replace(/\.(jpg|jpeg|png|gif)$/i, '.webp');
}

/**
 * Get primary (optimized) and fallback (original) URLs for an image
 * @deprecated Use getImageVariant instead for better variant support
 */
export function getImageUrls(originalUrl: string): { primary: string; fallback: string } {
	const webpUrl = getWebPUrl(originalUrl);
	return {
		primary: webpUrl,
		fallback: originalUrl,
	};
}

/**
 * Get image variant URL with Storage-first approach
 *
 * Priority order:
 * 1. Pre-generated variant from Supabase Storage (if storage_path exists)
 * 2. Fallback to imgproxy for dynamic generation (legacy/missing variants)
 * 3. Fallback to legacy image_url_webp (for old data)
 * 4. Fallback to original image_url
 *
 * @param image - Image object with storage_path, image_url, and optional image_url_webp
 * @param variant - Variant type to retrieve
 * @returns URL to the requested variant (or fallback)
 */
export function getImageVariant(
	image: {
		storage_path?: string;
		image_url: string;
		image_url_webp?: string | null;
	},
	variant: 'vision' | 'gallery' | 'card' | 'original'
): string {
	// Original always returns the original URL
	if (variant === 'original') {
		return image.image_url;
	}

	// If storage_path is available, use Storage-first approach
	if (image.storage_path) {
		// Build Storage URL for the pre-generated variant
		const storageVariantUrl = getVariantUrl(image.storage_path, variant);
		// Return Storage URL - variants are generated by Edge Function during upload
		return storageVariantUrl;
	}

	// Legacy data: No storage_path available
	// Fallback to image_url_webp for gallery/card (legacy data)
	if (variant === 'gallery' || variant === 'card') {
		return image.image_url_webp || image.image_url;
	}

	// Final fallback: Return original image_url
	return image.image_url;
}

/**
 * Image variant with optimized and original URLs
 */
export interface ImageVariant {
	id?: string; // jersey_image id from database
	originalUrl: string;
	optimizedUrl: string; // Gallery variant URL (for detail view)
	storagePath?: string; // Storage path for deriving variant URLs
	sortOrder: number;
	viewType: string | null;
}

/**
 * Create image variants from jersey_images data
 * Phase 2: Uses Storage-first approach for pre-generated gallery variants
 *
 * @param images - Array of jersey_images from database
 * @returns Array of ImageVariant objects with original and optimized URLs
 */
export function createImageVariants(
	images: Array<{
		id?: string;
		image_url: string;
		image_url_webp?: string | null;
		storage_path?: string;
		sort_order: number;
		view_type: string | null;
	}> | undefined
): ImageVariant[] {
	if (!images || images.length === 0) {
		return [];
	}

	return images
		.sort((a, b) => a.sort_order - b.sort_order)
		.map((img) => {
			// Use getImageVariant with 'gallery' variant (Storage-first with fallbacks)
			const optimizedUrl = getImageVariant(
				{
					storage_path: img.storage_path,
					image_url: img.image_url,
					image_url_webp: img.image_url_webp,
				},
				'gallery'
			);

			return {
				id: img.id,
				originalUrl: img.image_url,
				optimizedUrl,
				storagePath: img.storage_path,
				sortOrder: img.sort_order,
				viewType: img.view_type,
			};
		});
}

